// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-zG--sbEi45cTTt5bjPIDS07Ux2QvX-E',
    appId: '1:370861292171:web:79e682b82fb627d148328e',
    messagingSenderId: '370861292171',
    projectId: 'notes-7ac1f',
    authDomain: 'notes-7ac1f.firebaseapp.com',
    storageBucket: 'notes-7ac1f.firebasestorage.app',
    measurementId: 'G-JJQDY3X64Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1K8jvVgD_mHc63dQ-5m_clfU85VRCu0w',
    appId: '1:370861292171:android:2a7a23b73d7b553648328e',
    messagingSenderId: '370861292171',
    projectId: 'notes-7ac1f',
    storageBucket: 'notes-7ac1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpS4nKT3AW9NjEg1fBZ4b93N_J-vKUdz0',
    appId: '1:370861292171:ios:9ec97b1bdbdea9e148328e',
    messagingSenderId: '370861292171',
    projectId: 'notes-7ac1f',
    storageBucket: 'notes-7ac1f.firebasestorage.app',
    iosBundleId: 'com.example.notesManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpS4nKT3AW9NjEg1fBZ4b93N_J-vKUdz0',
    appId: '1:370861292171:ios:9ec97b1bdbdea9e148328e',
    messagingSenderId: '370861292171',
    projectId: 'notes-7ac1f',
    storageBucket: 'notes-7ac1f.firebasestorage.app',
    iosBundleId: 'com.example.notesManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-zG--sbEi45cTTt5bjPIDS07Ux2QvX-E',
    appId: '1:370861292171:web:17acd727ee05252e48328e',
    messagingSenderId: '370861292171',
    projectId: 'notes-7ac1f',
    authDomain: 'notes-7ac1f.firebaseapp.com',
    storageBucket: 'notes-7ac1f.firebasestorage.app',
    measurementId: 'G-LE3CZTQLEV',
  );
}
